# name: Docs
# on: [push, pull_request]
# jobs:
#   docs:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#       - name: Install dependencies
#         run: |
#           pip install sphinx sphinx_rtd_theme
#       - name: Sphinx build
#         run: |
#           make -C docs clean
#           make -C docs html
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
#         with:
#           publish_branch: gh-pages
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: _build/
#           force_orphan: true

name: Docs

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build documentation and commit
      run: |
          cd docs/
          sudo apt-get install python3-sphinx
          sphinx-apidoc -o . ../codebase/
          make html
          cd ..
          git config --global user.name "TejasPrabhu"
          git config --global user.email "tejas.prabhu29n@gmail.com"
          git add .
          git commit -m "Update documentation" -a || true
          git push
